{% set name = "pyramids" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/pyramids/archive/{{ version }}.tar.gz
  sha256: a645b9f8f935ae669b2bbc4a3a59afdf12b61b90c8671f2419407375ea3bdfce

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.11
    - pip >=23.2.1
  run:
    - python >=3.11
    - numpy >=1.25.2
    - hpc >=0.1.2
    - pip >=23.2.1
    - gdal >=3.7.0, <3.7.2
    - pandas >=2.0.0
    - geopandas >=0.13.2
    - Shapely >=2.0.1
    - pyproj >=3.6.0
    - PyYAML >=6.0.1
    - loguru >=0.7.0
    
test:
  imports:
    - pyramids

about:
  home: https://github.com/MAfarrag/pyramids
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: GIS utility package
  description: |
    GIS utility package.
  dev_url: https://github.com/MAfarrag/pyramids
  doc_url: https://pyramids-gis.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/pyramids/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
