{% set name = "pyramids" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/pyramids/archive/{{ version }}.tar.gz
  sha256: 2cb34eaf42ab6c145298efb4d9ee5c25fa615893d72efe9843e8c5dc0ada926a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip >=21.3.0
  run:
    - python >=3.7,<3.10
    - numpy >=1.21.2,<1.22.4
    - gdal >=3.3.3,<3.5.1
    - affine >=2.3.1
    - fiona >=1.8.21
    - pyproj >=3.4.0
    - pandas >=1.4.4
    - geopandas >=0.11.1
    - Rtree >=1.0.0
    - matplotlib >=3.5.3
    - shapely >=1.8.4
    - rasterio >=1.3.2
    - netCDF4 >=1.6.1
    - geopy >=2.2.0
    - pytest-cov >=3.0.0
    - pytest >=7.1.3
    
test:
  imports:
    - pyramids

about:
  home: https://github.com/MAfarrag/pyramids
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: GIS utility package
  description: |
    GIS utility package.
  dev_url: https://github.com/MAfarrag/pyramids
  doc_url: https://pyramids-gis.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/pyramids/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
