{% set python_min = "3.11" %}
{% set name = "pyramids" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/serapeum-org/pyramids/archive/{{ version }}.tar.gz
  sha256: 1611735535c6baa0d4d862c277437f34109e5f4ce5181f9d32bdeb433e99340e

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip >=24.3.1
    - setuptools
  run:
    - python >={{ python_min }}
    - geopandas >=1.0.0
    - hpc >=0.1.5
    - numpy >=2.0.0
    - pandas >=2.0.0
    - pyproj >=3.7.0
    - PyYAML >=6.0.0
    - Shapely >=2.0.0
    - gdal >=3.10.0
    - libgdal-netcdf >=3.10.0
    - libgdal-hdf4 >=3.10.0

  run_constrained:
    - cleopatra >=0.6.0
    - xarray >=2023.1.0
    - netCDF4 >=1.6.0
    - h5netcdf >=1.0.0
    - cftime >=1.6.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyramids

outputs:
  - name: {{ name }}

  - name: {{ name }}-viz
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
        - cleopatra >=0.6.0
    test:
      imports:
        - pyramids

  - name: {{ name }}-xarray
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
        - xarray >=2023.1.0
        - netcdf4 >=1.6.0
        - h5netcdf >=1.0.0
        - cftime >=1.6.0
    test:
      imports:
        - pyramids

about:
  home: https://github.com/serapeum-org/pyramids
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: GIS utility package
  description: |
    GIS utility package.
  dev_url: https://github.com/serapeum-org/pyramids
  doc_url: https://serapeum-org.github.io/pyramids
  doc_source_url: https://github.com/serapeum-org/pyramids/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
