{% set python_min = "3.11" %}
{% set name = "pyramids" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/pyramids/archive/{{ version }}.tar.gz
  sha256: 0e28f0947aa6b9516776dcbaebfd7b5bf1f2319bc122234bff1884e1dbd05ea2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip >=24.3.1
    - setuptools
  run:
    - python >={{ python_min }}
    - geopandas >=1.0.0
    - hpc >=0.1.5
    - loguru >=0.7.2
    - numpy >=2.0.0
    - pandas >=2.0.0
    - pyproj >=3.7.0
    - PyYAML >=6.0.0
    - Shapely >=2.0.0
    - gdal >=3.10.0
    - libgdal-netcdf >=3.10.0
    - libgdal-hdf4 >=3.10.0
    
  run_constrained:
    - cleopatra >=0.6.0


test:
  requires:
    - python {{ python_min }}
  imports:
    - pyramids

about:
  home: https://github.com/Serapieum-of-alex/pyramids
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: GIS utility package
  description: |
    GIS utility package.
  dev_url: https://github.com/Serapieum-of-alex/pyramids
  doc_url: https://serapieum-of-alex.github.io/pyramids
  doc_source_url: https://github.com/Serapieum-of-alex/pyramids/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
