{% set name = "pyramids" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/pyramids/archive/{{ version }}.tar.gz
  sha256: 5790857e5510fde84c8317e9abaafc18737c56ab83a39073510ecb24834f032a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip >=22.2.2
  run:
    - python >=3.9,<3.10
    - numpy >=1.21.2,<1.22.4
    - loguru >=0.6.0
    - pandas >=1.4.4
    - affine >=2.3.1
    - gdal >=3.4.3
    - Fiona >=1.8.21
    - geopandas >=0.11.1
    - geopy >=2.2.0
    - matplotlib >=3.5.3
    - netCDF4 >=1.6.1
    - pyproj >=3.4.0
    - rasterio >=1.2.10
    - Rtree >=1.0.0
    - Shapely >=1.8.4,<2
    - pytest >=7.1.3
    - pytest-cov >=3.0.0
    
test:
  imports:
    - pyramids

about:
  home: https://github.com/MAfarrag/pyramids
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: GIS utility package
  description: |
    GIS utility package.
  dev_url: https://github.com/MAfarrag/pyramids
  doc_url: https://pyramids-gis.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/pyramids/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
