{% set name = "pyramids" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/pyramids/archive/{{ version }}.tar.gz
  sha256: 4D4892BF0A743821199BCCF09C9DA3AB2B8B4950FA910CFB90BE0AFAD44F80C4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.15
    - pip >=22.3.1
  run:
      - python >=3.9,<3.15
      - gdal >=3.5.3
      - affine >=2.3.1
      - pandas >=1.4.4
      - geopandas >=0.12.2
      - Rtree >=1.0.0
      - Shapely >=1.8.4,<2
      - rasterio >=1.3.0
      - netCDF4 >=1.6.1
      - geopy >=2.2.0
      - pyproj >=3.4.0
      - loguru >=0.6.0
      - pytest >=7.1.3
      - pytest-cov =4.0.0
      - requests >=2.28.1
    
test:
  imports:
    - pyramids

about:
  home: https://github.com/MAfarrag/pyramids
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: GIS utility package
  description: |
    GIS utility package.
  dev_url: https://github.com/MAfarrag/pyramids
  doc_url: https://pyramids-gis.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/pyramids/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
