{% set python_min = "3.11" %}
{% set name = "pyramids" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/pyramids/archive/{{ version }}.tar.gz
  sha256: 6c4cb7f5326e72dae26251c9c73f9c9b7df49efa66b587a9d454af908c5c1488

build:
  skip: true

outputs:
  # 1. The core package – identical to what pip installs without extras
  - name: {{ pyramids }}
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv
      number: 0

    requirements:
      host:
        - python {{ python_min }}
        - pip
      run:
        - python >={{ python_min }}
        - numpy >=2.0.0
        - pandas >=2.0.0
        - geopandas >=1.0.0
        - pyproj >=3.7.0
        - shapely >=2.0.0
        - gdal >=3.10.0
        - hpc >=0.1.5
        - pyyaml >=6.0.0
        - loguru >=0.7.2
      run_constrained:
        - cleopatra >=0.5.1        # optional guard
    test:
      requires:
        - python {{ python_min }}
      imports:
        - pyramids
    about:
      home: https://github.com/MAfarrag/pyramids
      license: GPL-3.0-only
      license_family: GPL
      license_file: LICENSE.md
      summary: GIS utility package
      description: |
        GIS utility package.
      dev_url: https://github.com/MAfarrag/pyramids
      doc_url: https://pyramids-gis.readthedocs.io/
      doc_source_url: https://github.com/MAfarrag/pyramids/main/README.md

  # 2. A tiny meta-package that represents the [viz] extra
  - name: {{ pyramids }}-viz
    build:
      noarch: python
      number: 0
    requirements:
      run:
        - {{ pyramids }}                  # pulls in the core bits
        - cleopatra >=0.5.1               # adds the visualisation dep
    about:
      summary: "Meta-package that installs pyramids-gis plus the visualisation extra."
    extra:
      skip-lints:
        - build_script_missing

extra:
  recipe-maintainers:
    - MAfarrag