{% set name = "pyramids" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/pyramids/archive/{{ version }}.tar.gz
  sha256: 9e2a009ed3e98384f70abf632fb9eec7bf1a2035d5bd5020cd435edd2470749e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip >=21.3.0
  run:
    - python >=3.7
    - numpy >=1.21.2,<1.22.4
    - gdal >=3.3.3,<3.5.1
    - affine >=2.3.0
    - fiona >=1.8.20
    - pyproj >=3.2.1,<=3.4.0
    - pandas >=1.3.2,<1.4.3
    - geopandas >=0.10.2
    - matplotlib-base >=3.4.2,<3.6.0
    - shapely >=1.8.0
    - rasterio >=1.2.10
    - netCDF4 >=1.5.5,<1.5.9
    - geopy >=2.2.0
    - pytest-cov >=2.12.1
    - pytest >=6.2.5
test:
  imports:
    - pyramids

about:
  home: https://github.com/MAfarrag/pyramids
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: GIS utility package
  description: |
    GIS utility package.
  dev_url: https://github.com/MAfarrag/pyramids
  doc_url: https://pyramids-gis.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/pyramids/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
